### ISSUE TITLE
Support HTTP_X_FORWARDED_FOR

### ISSUE THREAD

**Issue by Serializator** [yireo/Yireo_CheckoutTester2#12]
`\Magento\Framework\HTTP\PhpEnvironment\Request::getClientIp($proxy)` directly returns the contents of `$_SERVER['HTTP_X_FORWARDED_FOR']` if the key exists in `$_SERVER`.

`HTTP_X_FORWARDED_FOR` is a comma separated list of IP's where the first IP in the array (when exploded) is the actual IP of the client and the other IP's are proxies in front of the actual web server.

What this causes is when the web server using Checkout Tester 2 is behind a proxy or some kind of load balancer, `\Magento\Framework\HTTP\PhpEnvironment\Request::getClientIp($proxy)` will return a string of comma separated IP's and Checkout Tester 2 checks if that string is equal to one of the IP's configured to have access, instead of taking the client IP from that comma separated string and checking that against one of the configured IP's.

**Comment by jissereitsma** [comment]
Thanks for the PR. Will merge because this first step makes sense. However, it seems then that with your PR the other IP addresses in `HTTP_X_FORWARDED_FOR` are not matched. This could yet lead to another issue of the same kind. In the end the `hasAccess` of the same helper class needs to be rewritten for this. I'll add some to do notes for this anyway, but that's for later - I have little time now. Thanks anyway for the contribution! Much appreciated!

**Comment by jissereitsma** [comment]
PR merged

**Comment by Serializator** [comment]
It sounds like that's a separate issue regarding the usage of proxies and VPNs in cases where, for example, someone works from a remote location and has to connect to a VPN to access an IP-restricted area.

In that case it would be better to refactor `getIpAddress()` into two separate functions, `getClientIp()` and `getProxyIps()` for example, and use those in the `hasAccess()` function to support the usage of proxies and VPNs.

I read that you have little time right now so if you agree (and want me to) I could refactor it and open a new PR if that'll help.
