### ISSUE TITLE
Registry Key

### ISSUE THREAD

**Issue by Jaspreet89** [yireo/Yireo_CheckoutTester2#5]
i am getting following conflict with one of my module,

Exception #0 (RuntimeException): Registry key "current_order" already exists

**Comment by yireo** [comment]
Could you share a bit more details than this? We have tested this for ourselves in Magento 2.1.7 and with the default Magento 2 core modules and do not have issues. Supplying every information that you can leads to more helpful information from our side.

**Comment by Jaspreet89** [comment]
Conflict is with 3rd party module OneStepCheckout-Registry key "current_order" already exists

dev/vendor/magento2-modules/OneStepCheckout/Block/Onepage/Success/Details.php(37): 
Magento\Framework\Registry->register('current_order', Object(Magento\Sales\Model\Order))

**Comment by yireo** [comment]
Thanks. This sounds more like a bug in OneStepCheckout extension. If somebody uses the registry object to call for `register()`, there is actually the need to call for `registry()` first. Our extension does so. If their module does so as well, there no longer is an issue.

Please note that this issue tracker is used to trick issues on our extension, not to fix support issues that occur in any site. It is an open source extension, not a free support gateway. Because this is not an issue with our extension specifically, I will close this ticket now.
